<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdef9ca500967e84127ae213fb7ff9669
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static $prefixesPsr0 = array (
        'o' => 
        array (
            'org\\bovigo\\vfs' => 
            array (
                0 => __DIR__ . '/..' . '/mikey179/vfsstream/src/main/php',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdef9ca500967e84127ae213fb7ff9669::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdef9ca500967e84127ae213fb7ff9669::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitdef9ca500967e84127ae213fb7ff9669::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
