<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Attendance_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get attendance by id
     */
    function get_attendances($id)
    {
        return $this->db->get_where('attendance',array('id'=>$id))->row_array();
    }

    function get_attendance($user_id)
    {
        $this->db->select('attendance.*,attendance_days.day,attendance_days.status,students.std_name');
        $this->db->join('students', 'students.id = attendance.student_id','left outer');
        $this->db->join('attendance_days', 'attendance_days.attend_id = attendance.id','left outer');
        $this->db->where('attendance.student_id', $user_id);
        $this->db->order_by('attendance.date_created', 'asc');
        $this->db->group_by('attendance.id');
        return $this->db->get('attendance')->result_array();
    }

    function get_std_attendance($std_id)
    {
        $this->db->select('attendance.*,attendance_days.day,attendance_days.status,students.std_name');
        $this->db->join('students', 'students.id = attendance.student_id','left outer');
        $this->db->join('attendance_days', 'attendance_days.attend_id = attendance.id','left outer');
        $this->db->where('attendance.student_id', $std_id);
        $this->db->order_by('attendance.date_created', 'asc');
        $this->db->group_by('attendance.id');
        return $this->db->get('attendance')->result_array();
    }

    function get_exist_attendance($user_id,$date){
        $this->db->where('MONTH(date_created)', $date);
        $this->db->where('student_id', $user_id);
        return $this->db->get('attendance')->row_array();
    }

    function get_exist_day($attend_id,$day){
        $this->db->where('day', $day);
        $this->db->where('attend_id', $attend_id);
        return $this->db->get('attendance_days')->row_array();
    }
    
    /*
     * Get all attendances count
     */
    function get_all_attendance_count()
    {
        $this->db->from('attendance');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all attendances
     */
    function get_all_attendance()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('attendance_days')->result_array();
    }
        
    /*
     * function to add new attendance
     */
    function add_attendance($params)
    {
        $this->db->insert('attendance',$params);
        return $this->db->insert_id();
    }

    function add_day($params)
    {
        $this->db->insert('attendance_days',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update attendance
     */
    function update_attendance($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('attendance',$params);
    }
    
    /*
     * function to delete class
     */
    function delete_attendance($id)
    {
        return $this->db->delete('attendance',array('id'=>$id));
    }

}
