<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Subject_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get subject by id
     */
    function get_subject($id)
    {
        return $this->db->get_where('subjects',array('id'=>$id))->row_array();
    }

    function get_std_subject($id)
    {
        $this->db->select('student_subjects.*,subjects.subject_name');
        $this->db->join('subjects', 'subjects.id=student_subjects.subject_id','left outer');
        $this->db->where('student_subjects.student_id', $id);
        return $this->db->get('student_subjects')->row_array();
    }
    
    function get_eadmission_no()
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('subject_name', $name);
        return $this->db->get('subjects')->result_array();
    }
    /*
     * Get all subjects count
     */
    function get_all_subjects_count()
    {
        $this->db->from('subjects');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all subjects
     */
    function get_all_subjects($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('subjects')->result_array();
    }

    function get_subject_by_class($class_id)
    {
        $this->db->select('*,subjects.subject_name');
        $this->db->join('subjects', 'subjects.id=classes_subjects.subject_id','left outer');
        $this->db->where('classes_subjects.class_id', $class_id);
        return $this->db->get('classes_subjects')->result_array();
    }

    function get_exist($name)
    {
        $this->db->order_by('id', 'desc');
        $this->db->where('subject_name', $name);
        return $this->db->get('subjects')->result_array();
    }
        
    /*
     * function to add new subject
     */
    function add_subject($params)
    {
        $this->db->insert('subjects',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update subject
     */
    function update_subject($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('subjects',$params);
    }
    
    /*
     * function to delete subject
     */
    function delete_subject($id)
    {
        return $this->db->delete('subjects',array('id'=>$id));
    }
}
